### ISSUE TITLE
Ad blocking doesn't work.

### ISSUE THREAD

**Issue by RalphORama** [MrYawnie/SpotifySkip#1]
System details:

```
Phone: HTC One m8
Android version: 6.0
SuperSU version: 2.76
xposed version: 82

Spotify version: 5.6.0.701 (free account)
SpotifySkip version: 2.0
Adaway version: 3.1.2
```

Everything works fine for me, except for ad blocking. I can play songs on-demand, disable shuffle, and skip as many songs as I want. However, when listening to playlists/albums/radio, I still get ads every 4 songs (about).

**Comment by MrYawnie** [comment]
I haven't had the chance to look into it yet. I haven't gotten any ads on mobile, and I don't have AdAway installed.. So those have to be some sort of local ads or something that gets handled differently. AdAway should block them though.When have you last updated AdAway hosts files? Have you changed the sources from http to https (they've changed!)?

**Comment by RalphORama** [comment]
I last updated a week ago, I'll update again now and see if that fixes anything.

**Comment by RalphORama** [comment]
Sorry for the late reply.
I updated my AdAway lists and added the [SomeoneWhoCares source](http://someonewhocares.org/hosts/hosts), that has solved my issue with ads appearing.

**Comment by davex2012** [comment]
where to download apk files?

**Comment by MrYawnie** [comment]
@davex2012 https://github.com/MrYawnie/SpotifySkip/releases

**Comment by davex2012** [comment]
@Mr.Yawnie update for new version.?
