### ISSUE TITLE
Ads in latest version 

### ISSUE THREAD

**Issue by davex2012** [MrYawnie/SpotifySkip#2]
Ads in latest version of Spotify....  Updates?

**Comment by MrYawnie** [comment]
Ad blocking is not a feature of SpotifySkip, thus it won't get updated. Also, it is a feature I won't be adding to this module. You can use existing ad-blocking methods.

**Comment by davex2012** [comment]
Okay thanks.. where can I find existing blocking methods?

**Comment by davex2012** [comment]
Btw shuffle is not disabled. M
